name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v4
        with:
          name: nuget packages
          path: ./Hamunii.MonoMod.RuntimeDetour.HookGen.MSBuild/bin/Release/*.nupkg

      - name: Push NuGet package
        if: github.ref_type == 'tag'
        run: |
          dotnet nuget push ./Hamunii.MonoMod.RuntimeDetour.HookGen.MSBuild/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
